apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-backend
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
      app: node-backend
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: PGUSER
              value: {{ .Values.backend.env.PGUSER | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: myapp-database-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              value: {{ .Values.backend.env.PGDATABASE | quote }}
            - name: PGHOST
              value: {{ .Values.backend.env.PGHOST | quote }}
            - name: PGPORT
              value: {{ .Values.backend.env.PGPORT | quote }}

      imagePullSecrets:
        - name: my-registry-secret
